version: '3.8'

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data_django28:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_test
      POSTGRES_PASSWORD: postgres_test
      POSTGRES_DB: postgres_test
    restart: always
    ports:
    - "5432:5432"

volumes:
  postgres_data_django28:
